/* ============================================================================
   Phase 4 — Setup 03: Roles & Grants (RBAC, least privilege)
   Gaming Compliance & Risk Intelligence Platform (Snowflake edition)

   Creates six functional roles and grants each ONLY what its job requires.
   Run after 01 (warehouses) and 02 (database/schemas).

   Roles (least privilege):
     PLATFORM_OWNER     platform admin; inherits all functional roles
     DATA_ENGINEER      builds & loads RAW->STAGING->CORE->ANALYTICS->REPORTING
     COMPLIANCE_ANALYST reads REPORTING + ANALYTICS (investigate alerts/cases)
     COMPLIANCE_MANAGER analyst + read CORE (oversight)
     BI_REPORTING       Power BI service role; reads REPORTING views ONLY
     READ_ONLY_AUDITOR  read-only across all data layers for audit

   No end-user names or secrets are hardcoded. Role->user grants are shown as
   commented placeholders at the bottom. All data is SYNTHETIC.
   ============================================================================ */

-- SECURITYADMIN creates roles and manages grants (has MANAGE GRANTS globally).
USE ROLE SECURITYADMIN;

/* ---- 1. Create functional roles ------------------------------------------- */
CREATE ROLE IF NOT EXISTS PLATFORM_OWNER     COMMENT = 'Platform admin for GAMING_COMPLIANCE_DB.';
CREATE ROLE IF NOT EXISTS DATA_ENGINEER      COMMENT = 'Builds and loads the layered model.';
CREATE ROLE IF NOT EXISTS COMPLIANCE_ANALYST COMMENT = 'Reads reporting + analytics for investigations.';
CREATE ROLE IF NOT EXISTS COMPLIANCE_MANAGER COMMENT = 'Analyst privileges + curated core read (oversight).';
CREATE ROLE IF NOT EXISTS BI_REPORTING       COMMENT = 'Power BI service role; reporting views only.';
CREATE ROLE IF NOT EXISTS READ_ONLY_AUDITOR  COMMENT = 'Read-only across all data layers for audit.';

/* ---- 2. Role hierarchy (roll up so SYSADMIN can manage everything) --------- */
GRANT ROLE COMPLIANCE_ANALYST TO ROLE COMPLIANCE_MANAGER;   -- manager is a superset of analyst
GRANT ROLE DATA_ENGINEER      TO ROLE PLATFORM_OWNER;
GRANT ROLE COMPLIANCE_MANAGER TO ROLE PLATFORM_OWNER;
GRANT ROLE BI_REPORTING       TO ROLE PLATFORM_OWNER;
GRANT ROLE READ_ONLY_AUDITOR  TO ROLE PLATFORM_OWNER;
GRANT ROLE PLATFORM_OWNER     TO ROLE SYSADMIN;             -- SYSADMIN oversees the platform

/* ---- 3. Warehouse usage (each role only touches the compute it needs) ------ */
GRANT USAGE ON WAREHOUSE WH_INGESTION    TO ROLE DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE WH_TRANSFORM    TO ROLE DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE WH_DATA_SCIENCE TO ROLE DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE WH_REPORTING    TO ROLE BI_REPORTING;
GRANT USAGE ON WAREHOUSE WH_REPORTING    TO ROLE COMPLIANCE_ANALYST;
GRANT USAGE ON WAREHOUSE WH_REPORTING    TO ROLE READ_ONLY_AUDITOR;
-- COMPLIANCE_MANAGER inherits COMPLIANCE_ANALYST's WH_REPORTING usage.

/* ---- 4. Database usage (required before any schema access) ----------------- */
GRANT USAGE ON DATABASE GAMING_COMPLIANCE_DB TO ROLE DATA_ENGINEER;
GRANT USAGE ON DATABASE GAMING_COMPLIANCE_DB TO ROLE COMPLIANCE_ANALYST;
GRANT USAGE ON DATABASE GAMING_COMPLIANCE_DB TO ROLE COMPLIANCE_MANAGER;
GRANT USAGE ON DATABASE GAMING_COMPLIANCE_DB TO ROLE BI_REPORTING;
GRANT USAGE ON DATABASE GAMING_COMPLIANCE_DB TO ROLE READ_ONLY_AUDITOR;

/* ---- 5a. DATA_ENGINEER : build + read/write the pipeline ------------------- */
-- Build schemas: usage + create object privileges. Engineer OWNS what it creates
-- (so it gets read/write on those objects automatically).
GRANT USAGE ON SCHEMA GAMING_COMPLIANCE_DB.RAW       TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA GAMING_COMPLIANCE_DB.STAGING   TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA GAMING_COMPLIANCE_DB.CORE      TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA GAMING_COMPLIANCE_DB.ANALYTICS TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA GAMING_COMPLIANCE_DB.REPORTING TO ROLE DATA_ENGINEER;
GRANT USAGE ON SCHEMA GAMING_COMPLIANCE_DB.UTILITY   TO ROLE DATA_ENGINEER;

-- Object-creation privileges on the build schemas.
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE STREAM, CREATE TASK,
      CREATE FILE FORMAT, CREATE STAGE, CREATE PROCEDURE, CREATE FUNCTION
   ON SCHEMA GAMING_COMPLIANCE_DB.RAW       TO ROLE DATA_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE STREAM, CREATE TASK,
      CREATE FILE FORMAT, CREATE STAGE, CREATE PROCEDURE, CREATE FUNCTION
   ON SCHEMA GAMING_COMPLIANCE_DB.STAGING   TO ROLE DATA_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE STREAM, CREATE TASK,
      CREATE PROCEDURE, CREATE FUNCTION
   ON SCHEMA GAMING_COMPLIANCE_DB.CORE      TO ROLE DATA_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE STREAM, CREATE TASK,
      CREATE PROCEDURE, CREATE FUNCTION
   ON SCHEMA GAMING_COMPLIANCE_DB.ANALYTICS TO ROLE DATA_ENGINEER;
GRANT CREATE VIEW
   ON SCHEMA GAMING_COMPLIANCE_DB.REPORTING TO ROLE DATA_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE
   ON SCHEMA GAMING_COMPLIANCE_DB.UTILITY   TO ROLE DATA_ENGINEER;

/* ---- 5b. COMPLIANCE_ANALYST : read REPORTING + ANALYTICS (SELECT only) ----- */
GRANT USAGE ON SCHEMA GAMING_COMPLIANCE_DB.REPORTING TO ROLE COMPLIANCE_ANALYST;
GRANT USAGE ON SCHEMA GAMING_COMPLIANCE_DB.ANALYTICS TO ROLE COMPLIANCE_ANALYST;
GRANT SELECT ON ALL    TABLES IN SCHEMA GAMING_COMPLIANCE_DB.REPORTING TO ROLE COMPLIANCE_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GAMING_COMPLIANCE_DB.REPORTING TO ROLE COMPLIANCE_ANALYST;
GRANT SELECT ON ALL    VIEWS  IN SCHEMA GAMING_COMPLIANCE_DB.REPORTING TO ROLE COMPLIANCE_ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA GAMING_COMPLIANCE_DB.REPORTING TO ROLE COMPLIANCE_ANALYST;
GRANT SELECT ON ALL    TABLES IN SCHEMA GAMING_COMPLIANCE_DB.ANALYTICS TO ROLE COMPLIANCE_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GAMING_COMPLIANCE_DB.ANALYTICS TO ROLE COMPLIANCE_ANALYST;
GRANT SELECT ON ALL    VIEWS  IN SCHEMA GAMING_COMPLIANCE_DB.ANALYTICS TO ROLE COMPLIANCE_ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA GAMING_COMPLIANCE_DB.ANALYTICS TO ROLE COMPLIANCE_ANALYST;

/* ---- 5c. COMPLIANCE_MANAGER : analyst (inherited) + curated CORE read ------ */
GRANT USAGE ON SCHEMA GAMING_COMPLIANCE_DB.CORE TO ROLE COMPLIANCE_MANAGER;
GRANT SELECT ON ALL    TABLES IN SCHEMA GAMING_COMPLIANCE_DB.CORE TO ROLE COMPLIANCE_MANAGER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GAMING_COMPLIANCE_DB.CORE TO ROLE COMPLIANCE_MANAGER;

/* ---- 5d. BI_REPORTING : Power BI service role; REPORTING views ONLY -------- */
GRANT USAGE ON SCHEMA GAMING_COMPLIANCE_DB.REPORTING TO ROLE BI_REPORTING;
GRANT SELECT ON ALL    VIEWS IN SCHEMA GAMING_COMPLIANCE_DB.REPORTING TO ROLE BI_REPORTING;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GAMING_COMPLIANCE_DB.REPORTING TO ROLE BI_REPORTING;

/* ---- 5e. READ_ONLY_AUDITOR : SELECT across all data layers (no writes) ----- */
GRANT USAGE ON SCHEMA GAMING_COMPLIANCE_DB.RAW       TO ROLE READ_ONLY_AUDITOR;
GRANT USAGE ON SCHEMA GAMING_COMPLIANCE_DB.STAGING   TO ROLE READ_ONLY_AUDITOR;
GRANT USAGE ON SCHEMA GAMING_COMPLIANCE_DB.CORE      TO ROLE READ_ONLY_AUDITOR;
GRANT USAGE ON SCHEMA GAMING_COMPLIANCE_DB.ANALYTICS TO ROLE READ_ONLY_AUDITOR;
GRANT USAGE ON SCHEMA GAMING_COMPLIANCE_DB.REPORTING TO ROLE READ_ONLY_AUDITOR;
GRANT USAGE ON SCHEMA GAMING_COMPLIANCE_DB.UTILITY   TO ROLE READ_ONLY_AUDITOR;
-- SELECT on existing + future tables and views in every data schema.
GRANT SELECT ON ALL    TABLES IN DATABASE GAMING_COMPLIANCE_DB TO ROLE READ_ONLY_AUDITOR;
GRANT SELECT ON FUTURE TABLES IN DATABASE GAMING_COMPLIANCE_DB TO ROLE READ_ONLY_AUDITOR;
GRANT SELECT ON ALL    VIEWS  IN DATABASE GAMING_COMPLIANCE_DB TO ROLE READ_ONLY_AUDITOR;
GRANT SELECT ON FUTURE VIEWS  IN DATABASE GAMING_COMPLIANCE_DB TO ROLE READ_ONLY_AUDITOR;
-- OPTIONAL (ACCOUNTADMIN): query-history access for audit, e.g.
--   USE ROLE ACCOUNTADMIN;
--   GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE READ_ONLY_AUDITOR;

/* ---- 6. Assign roles to users (PLACEHOLDERS — do not hardcode real users) --
   USE ROLE SECURITYADMIN;
   GRANT ROLE DATA_ENGINEER      TO USER <YOUR_ENGINEER_USER>;
   GRANT ROLE COMPLIANCE_ANALYST TO USER <YOUR_ANALYST_USER>;
   GRANT ROLE BI_REPORTING       TO USER <YOUR_POWERBI_SERVICE_USER>;
   -- Optionally set a default role/warehouse per user:
   -- ALTER USER <USER> SET DEFAULT_ROLE = COMPLIANCE_ANALYST
   --                       DEFAULT_WAREHOUSE = WH_REPORTING;
   ---------------------------------------------------------------------------- */

SHOW ROLES LIKE '%COMPLIANCE%';
SHOW GRANTS TO ROLE BI_REPORTING;
